### ISSUE TITLE
SQL query composition

### ISSUE THREAD

**Issue by mudrd8mz** [moodleuulm/moodle-block_cohortspecifichtml#2]
The SQL composed in `block_cohortspecifichtml_cohorts_is_member()` should be improved to

* Use placeholders (named or anonymous) instead of directly concatenating the SQL with incoming parameter. This is a good practise even when the parameters comes from safe sources like `$USER->id` or the block config.
* Make use of `$DB->get_in_or_equal()`

**Comment by Kathrin84** [comment]
Hi David,
thanks for these hints. 
I improved the function in this commit:
https://github.com/moodleuulm/moodle-block_cohortspecifichtml/commit/70feaeb417fb2cd53af3967bddc67d22f806abfa

I'll close this issue at this point.
Best, Kathrin
